spring:
#  config:
#    activate:
#      on-profile: production
  datasource:
#    url: jdbc:mysql://13.209.38.201:3306/silvernote?serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/silvernote?serverTimezone=Asia/Seoul
    username: jin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: none   # create라면 생성할 때 있는 테이블을 지우고 다시 생성해준다 drop & create
    properties:
      hibernate:
        # show-sql: true
        format_sql: true
        default_batch_fetch_size: 100

    open-in-view: true # false < 트랜젝션 내 지연로딩 초기화 작업 필요

#---
#
#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    url: jdbc:mysql://localhost:3306/silvernote?serverTimezone=Asia/Seoul
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#
#  jpa:
#    hibernate:
#      ddl-auto: create   # create라면 생성할 때 있는 테이블을 지우고 다시 생성해x준다 drop & create
#    properties:
#      hibernate:
#        # show-sql: true
#        format_sql: true
#        default_batch_fetch_size: 100
#
#    open-in-view: true # false < 트랜젝션 내 지연로딩 초기화 작업 필요


logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace
